# Generated by Django 3.2.9 on 2021-11-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myuploadfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('master_roll', models.FileField(null=True, upload_to='')),
                ('responses', models.FileField(null=True, upload_to='')),
                ('postive_marks', models.IntegerField(null=True)),
                ('negative_marks', models.IntegerField(null=True)),
            ],
        ),
    ]
